apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-hello-world-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: <your-domain-or-ip>           # Replace this with your domain or Minikube IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-hello-world-service
            port:
              number: 80

