name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: source code checkout
      uses: actions/checkout@v3

    - name: install Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install node dependencies from package-lock.json
      run: npm ci

    - name: linting
      run: |
        npm install eslint --save-dev
        npm run lint

    - name: testing
      run: npm test
      
    - name: Set env variables  
      run: |
       echo "DOCKER_SERVER=${{ vars.DOCKER_SERVER }}" >> $GITHUB_ENV
       echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
       
    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
         registry: ghcr.io
         username: ${{ vars.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASS }}

    - name: Build and push Docker image
      run: |
       docker build -t $DOCKER_SERVER:$TAG .
       docker push $DOCKER_SERVER:$TAG
      

