name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: source code checkout
      uses: actions/checkout@v3

    - name: install Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install node dependencies from package-lock.json
      run: npm ci

    - name: linting
      run: |
        npm install eslint --save-dev
        npm run lint

    - name: testing
      run: npm test
